apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ include "peakwell.namespace" . }}
  labels:
    {{- include "peakwell.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nslookup backend.{{ include "peakwell.namespace" . }}.svc.cluster.local; do
                echo "Waiting for backend service..."; sleep 3
              done
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ include "peakwell.namespace" . }}
  labels:
    {{- include "peakwell.labels" . | nindent 4 }}
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
