apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: peakwell-ingress
  namespace: {{ include "peakwell.namespace" . }}
  labels:
    {{- include "peakwell.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
