apiVersion: v1
kind: Secret
metadata:
  name: peakwell-secrets
  namespace: {{ include "peakwell.namespace" . }}
  labels:
    {{- include "peakwell.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD:            {{ .Values.secrets.mysqlRootPassword | quote }}
  SPRING_DATASOURCE_PASSWORD:     {{ .Values.secrets.springDatasourcePassword | quote }}
  KEYCLOAK_CLIENT_SECRET:         {{ .Values.secrets.keycloakClientSecret | quote }}
  KC_DB_PASSWORD:                 {{ .Values.secrets.keycloakDbPassword | quote }}
  SPRING_MAIL_PASSWORD:           {{ .Values.secrets.springMailPassword | quote }}
  GROQ_API_KEY:                   {{ .Values.secrets.groqApiKey | quote }}
  NUTRITION_API_KEY:              {{ .Values.secrets.nutritionApiKey | quote }}
  AI_API_KEY:                     {{ .Values.secrets.aiApiKey | quote }}
  IA_FACE_API_KEY:                {{ .Values.secrets.iaFaceApiKey | quote }}
  AI_FACE_API_SECRET:             {{ .Values.secrets.aiFaceApiSecret | quote }}
  STRIPE_SECRET_KEY:              {{ .Values.secrets.stripeSecretKey | quote }}
  JWT_SECRET:                     {{ .Values.secrets.jwtSecret | quote }}
  CAPTCHA_HMAC_SECRET:            {{ .Values.secrets.captchaHmacSecret | quote }}
  CAPTCHA_JWT_SECRET:             {{ .Values.secrets.captchaJwtSecret | quote }}
