apiVersion: v1
kind: Secret
metadata:
  name: peakwell-secrets
  namespace: peakwell
type: Opaque
stringData:
  # ── Database ───────────────────────────────────────────────────────────
  MYSQL_ROOT_PASSWORD: "peakwell"
  SPRING_DATASOURCE_PASSWORD: "peakwell"

  # ── Keycloak ───────────────────────────────────────────────────────────
  KEYCLOAK_CLIENT_SECRET: "g6PZR6A8vNOoW7MOYzJ8pCH4UUox77xi"
  KC_DB_PASSWORD: "peakwell"

  # ── Mail ───────────────────────────────────────────────────────────────
  SPRING_MAIL_PASSWORD: "xhjsfsxfbcbrelts"

  # ── AI APIs ────────────────────────────────────────────────────────────
  GROQ_API_KEY: "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"
  NUTRITION_API_KEY: "ggJEPcXVIlcCLfJaIW28QKEGFEEttcwsinBDM3Nh"
  AI_API_KEY: "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"

  # ── Face++ ─────────────────────────────────────────────────────────────
  IA_FACE_API_KEY: "JqflDziXLUo-bG3zPj11ZTnAMBFQZ0Sz"
  AI_FACE_API_SECRET: "RB3PO2bsCGVPYPzobmBxk0F1qKNgUOij"

  # ── Stripe ─────────────────────────────────────────────────────────────
  STRIPE_SECRET_KEY: "sk_test_51TCpiOQRBlglb0TZOi5yEYnMWP23Kz131ZcEGCEO2jAz2vquIU2r5mgkTO8lqPVqnplkkjV0njqpZXp1c2iyUZAm003adOlcTr"

  # ── JWT & Captcha ──────────────────────────────────────────────────────
  JWT_SECRET: "mySuperSecretKeyThatIsAtLeast32CharactersLong123"
  CAPTCHA_HMAC_SECRET: "min32charsecretchangeme1234567890"
  CAPTCHA_JWT_SECRET: "anotherlongrandomsecretforjwt5678"
