apiVersion: v1
kind: ConfigMap
metadata:
  name: peakwell-config
  namespace: peakwell
data:
  # ── Keycloak container config ─────────────────────────────────────────
  KC_HTTP_ENABLED: "true"
  KC_HEALTH_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_DB: "mysql"
  KC_DB_URL: "jdbc:mysql://mysql:3306/keycloak?createDatabaseIfNotExist=true&autoReconnect=true&connectTimeout=10000&socketTimeout=30000"
  KC_DB_USERNAME: "root"

  # ── Database ──────────────────────────────────────────────────────────
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/peakwell?createDatabaseIfNotExist=true&zeroDateTimeBehavior=convertToNull"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_JPA_SHOW_SQL: "false"

  # ── Keycloak ──────────────────────────────────────────────────────────
  KEYCLOAK_SERVER_URL: "http://keycloak:8080"
  KEYCLOAK_PUBLIC_URL: "http://192.168.1.231.nip.io:30180"
  KC_HOSTNAME: "http://192.168.1.231.nip.io:30180"
  KEYCLOAK_REALM: "peakwell"
  KEYCLOAK_CLIENT_ID: "spring-client"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak:8080/realms/peakwell/protocol/openid-connect/certs"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://192.168.1.231.nip.io:30180/realms/peakwell"

  # ── App URLs ──────────────────────────────────────────────────────────
  APP_FRONTEND_URL: "http://192.168.1.231.nip.io"
  APP_PUBLIC_URL: "http://192.168.1.231.nip.io/peakwell"
  APP_VERIFY_EMAIL_REDIRECT_URL: "http://192.168.1.231.nip.io/auth/login"

  # ── AI microservices — internal cluster DNS ───────────────────────────
  PEAKWELL_AI_ML_URL: "http://ai-ml:8001"
  PEAKWELL_AI_SYMPTOM_URL: "http://ai-symptom:8002"
  PEAKWELL_AI_NUTRITION_URL: "http://ai-nutrition:8003"
  PEAKWELL_AI_SPORT_URL: "http://ai-sport:8004"

  # ── External AI APIs ──────────────────────────────────────────────────
  GROQ_API_URL: "https://api.groq.com/openai/v1/chat/completions"
  AI_MODEL: "moonshotai/Kimi-K2-Instruct-0905"
  AI_API_URL: "https://router.huggingface.co/v1/chat/completions"
  AI_FACE_API_URL: "https://api-us.faceplusplus.com/facepp/v3/compare"

  # ── Mail ──────────────────────────────────────────────────────────────
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_USERNAME: "achrefpatron38@gmail.com"
  APP_MAIL_FROM: "achrefpatron38@gmail.com"

  # ── Stripe ────────────────────────────────────────────────────────────
  STRIPE_CURRENCY: "tnd"
  CONSULTATION_PRICE: "5000"
  PAYMENT_CURRENCY: "usd"
  PAYMENT_PRICE_CONSULTATION: "5000"
  PAYMENT_PRICE_SPORTS_EVENT: "2000"
  PAYMENT_PRICE_NUTRITION_PLAN: "9900"
  PAYMENT_PRICE_SUBSCRIPTION_MONTHLY: "1990"
  PAYMENT_PRICE_SUBSCRIPTION_YEARLY: "14900"

  # ── JWT ───────────────────────────────────────────────────────────────
  JWT_EXPIRATION: "86400000"
